global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-api'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['api:8080']  # "api" é o nome do serviço no Docker Compose